import type { Project } from "~/types";

const PROJECTS: Project[] = [
  {
    id: "teachsimple",
    title: "Educational Platform",
    brand: "Teach Simple LLC.",
    type: "professional",
    tech: [
      "Nuxt.js",
      "Node.js",
      "Vue.js",
      "EC2",
      "Elasticsearch",
      "Stripe",
      "S3 Storage",
      "Cloudinary",
      "Clickbank",
      "Priority Hints",
    ],
    intro: [
      "Teach Simple provides unlimited access to teaching resources for a low monthly fee.",
      "The website provides a common platform where teachers can upload their products.",
      "A user gets access to unlimited resources such as activities, worksheets, ebooks, book companions etc. in various languages.",
    ],
    features: [
      {
        id: "feature1",
        name: "Advanced Content Distribution System",
        description: [
          "Built a scalable content delivery network that optimizes resource loading times across various regions",
          "Implemented intelligent caching strategies reducing server load by 50%",
        ],
      },
      {
        id: "feature2",
        name: "Product Upload",
        description: [
          "Teachers can upload their products to the platform",
          "Products can be in different languages and formats",
        ],
      },
      {
        id: "feature3",
        name: "Product Management",
        description: [
          "Allows teachers to manage their products on the platform where they can add, edit and delete their products",
        ],
      },
    ],
    imgUrl: "teachsimple.jpg",
    mockupImg: "teachsimple.png",
    video: "https://www.youtube.com/watch?v=qY6-iODMcXE",
    webUrl: "https://teachsimple.com",
    display: true,
  },
  {
    id: "zentaflowplan",
    title: "Cash Flow Manager",
    brand: "Zentapon Pty. Ltd.",
    type: "professional",
    tech: [
      "Next.js",
      "Nest.js",
      "Node.js",
      "TypeScript",
      "Tailwind CSS",
      "Prisma",
      "Basiq",
      "Plaid",
      "AWS S3",
      "Render",
    ],
    intro: [
      "The application focuses on managing cashflow for present and future transactions based on present entries.",
      "It primarily solves complex financial data management challenges by using a scalable architecture that handles thousands of transactions while maintaining real-time performance while integrating with Bank-Feed API.",
    ],
    features: [
      {
        id: "feature1",
        name: "Interactive Charts & Dynamic Tables",
        image: true,
        description: [
          "Usage of interactive line and bar charts",
          "Use of dynamic, sortable and expandable tables",
          "Import/Export transactions from any data file to custom output file",
        ],
      },
      {
        id: "feature2",
        name: "Intelligent Cash Flow Prediction Engine",
        description: [
          "Built an advanced prediction engine using historical data patterns to forecast future cash flows with 90% accuracy",
          "Implemented machine learning algorithms to categorize transactions automatically and improve forecasting precision",
        ],
      },
      {
        id: "feature3",
        name: "Open Bank API Integration",
        image: true,
        description: [
          "The website is integrated with Plaid API for users to get benefits from their own bank accounts",
          "A user is able to create multiple scenarios to mock up real bank like feature and estimated future earnings",
          "Transactions for real bank accounts can be copied to a scenario and user can see the future cashflow based on that",
        ],
      },
      {
        id: "feature4",
        name: "Complex Data Synchronization System",
        image: true,
        description: [
          "Implemented a robust synchronization system that handles concurrent updates from multiple data sources (bank feeds, manual entries, and scheduled transactions) while maintaining data consistency",
          "Developed conflict resolution algorithms to handle overlapping transactions and prevent duplicate entries",
        ],
      },
      {
        id: "feature5",
        name: "Real Time Currency Conversion",
        image: true,
        description: [
          "Real time currency conversion based on the latest exchange rates",
          "User can add transactions in different currencies based on scenarios and see the total amount in the base currency",
        ],
      },
    ],
    imgUrl: "zentaflowplan.webp",
    mockupImg: "zentaflowplan.webp",
    webUrl: "https://cashflow-clone.vercel.app",
    appUrl: "https://zentapon.com.au",
    display: true,
  },
  {
    id: "edukurve",
    title: "Learning Management System",
    brand: "Inspired by Jan",
    type: "personal",
    tech: [
      "Next.js",
      "React.js",
      "Node.js",
      "Stripe",
      "AWS S3",
      "Arcjet",
      "Tailwind CSS",
      "Shadcn UI",
      "Neon DB",
    ],
    intro: [
      "Edukurve is a modern Learning Management System built with Next.js 15 and React 19, designed to provide a comprehensive platform for online education.",
      "The system features AI-powered learning experiences, secure payment processing through Stripe, and robust course management capabilities.",
      "It supports both student and instructor workflows with real-time progress tracking, file management via AWS S3, and responsive design.",
    ],
    features: [
      {
        id: "feature1",
        name: "Course Management & Content Creation",
        description: [
          "Rich text editor with TipTap for creating engaging course content and lesson descriptions",
          "Drag-and-drop interface for organizing chapters and lessons in a structured hierarchy",
          "File upload system supporting videos, images, and documents through AWS S3 integration",
          "Course status management with draft, published, archived, and deleted states",
        ],
      },
      {
        id: "feature2",
        name: "Student Learning Experience",
        description: [
          "Interactive dashboard displaying enrolled courses with progress tracking and completion status",
          "Video lesson playback with thumbnail previews and descriptive content for each lesson",
          "Course discovery page with filtering by category, level, and price for easy browsing",
          "Secure payment processing using Stripe for course purchases with webhook integration",
        ],
      },
      {
        id: "feature3",
        name: "Authentication & User Management",
        description: [
          "Email-based authentication with verification system using Resend for secure account creation",
          "Role-based access control supporting students, instructors, and admin user types",
          "Session management with IP tracking and user agent logging for security monitoring",
          "User profile management with avatar uploads and account information updates",
        ],
      },
      {
        id: "feature4",
        name: "Analytics & Progress Tracking",
        description: [
          "Real-time enrollment statistics and course performance metrics for administrators",
          "Individual student progress tracking with lesson completion status and time tracking",
          "Interactive charts and visualizations using Recharts for data presentation",
          "Comprehensive dashboard showing course popularity and user engagement patterns",
        ],
      },
      {
        id: "feature5",
        name: "Technical Infrastructure",
        description: [
          "Modern tech stack with TypeScript, Tailwind CSS v4, and Prisma ORM for type safety",
          "Server-side rendering with Next.js App Router for optimal performance and SEO",
          "Rate limiting and security measures using Arcjet for API protection",
          "Responsive design with dark/light theme switching and mobile-first approach",
        ],
      },
    ],
    imgUrl: "edukurve.webp",
    mockupImg: "edukurve.webp",
    webUrl: "https://edukurve.vercel.app",
    display: true,
  },
  {
    id: "homewayz",
    title: "Real Estate Dashboard",
    brand: "HomeWayz",
    type: "professional",
    tech: ["Vue.js", "Node.js"],
    intro: [
      "HomeWayz is the first of its kind workflow solution. It is established in 2018 by an Agent for Agents.",
      "It's a real estate application consisting of a huge database of active properties for rent and sale.",
      "I handled the frontend development in agent/client dashboard system.",
    ],
    features: [
      {
        id: "feature1",
        name: "Route Map generation",
        description: [
          "It's one of the key feature of HomeWayz application",
          "It helps agents to create routes by choosing any of the properties and entering the time/data",
          "The routes can be assigned different states like saved, pending, confirmed based on its status",
          "All scheduled routes can be used by clients to generate a route map for that particular day to visit included properties",
        ],
      },
      {
        id: "feature2",
        name: "Google Map & Search Integration",
        description: [
          "Google map integration is included in the application that works and route generation utility",
          "Consists of a fully featured search system with different functionalities",
          "Allows users to search MLS properties by google location search",
        ],
      },
      {
        id: "feature3",
        name: "Assignment of properties to clients by agents",
        description: [
          "Agents are able to assign properties to clients that they find would align with clients needs and wants",
          "The properties can be saved and requested by clients for a tour",
        ],
      },
      {
        id: "feature4",
        name: "Needs/Wants for client side dashboard",
        description: [
          "Clients are able to input their needs and wants which are then matched with MLS properties",
          "Based on client's needs/wants, a match percent is generated that helps clients determine their available options",
          "Needs and wants are also assigned by agents to respective clients by having a thorough conversation with what a client need",
        ],
      },
      {
        id: "feature5",
        name: "Messaging & email system",
        description: [
          "A two way communication channel between agents and clients",
          "Clients are duly notified for any updates in MLS properties that might match with their requirements.",
          "A fully integrated email and phone system",
        ],
      },
    ],
    imgUrl: "homewayz.webp",
    mockupImg: "homewayz.webp",
    video: "https://www.youtube.com/watch?v=knBgZnPthMY",
    webUrl: "https://app.homewayz.io",
    appUrl: "https://homewayz.io",
    display: true,
  },
  {
    id: "askncollab",
    title: "Ask and Collaborate",
    brand: "Inspired by Stack Overflow",
    type: "personal",
    tech: ["Next.js", "Tailwind CSS", "Shadcn UI", "Supabase", "Zod"],
    intro: [
      "This is a Q&A platform built with NextJS with a focus on collaboration and community engagement.",
      "It includes authentication and is fully responsive.",
      "Dynamically renders the questions and answers created by the user.",
      "Users can upvote and downvote the questions and answers.",
    ],
    imgUrl: "askncollab.png",
    mockupImg: "askncollab.png",
    webUrl: "https://ask-and-collab.vercel.app",
    display: true,
  },
  {
    id: "northstate",
    title: "Insurance Website",
    brand: "NorthState Financial Services Corporation",
    type: "professional",
    tech: ["JavaScript", "HTML", "CSS", "PHP"],
    intro: [
      "The organization provides affordable solutions to financial security of customers",
      "Consists of a variety of insurance and loan options which users can opt based on their needs",
      "Includes calculations and comparisons of insurance options provided by other brands",
    ],
    features: [
      {
        id: "feature1",
        name: "Multiple Forms",
        image: true,
        description: [
          "Each insurance type has its own specific form  that is submitted to understand customer's needs",
          "A quote is generated based on client's requirements",
        ],
      },
      {
        id: "feature2",
        name: "Email system & Fully responsive",
        image: true,
        description: [
          "Email integration to send the owner notifications about a customer's application for its service",
          "Beautiful UI layout made from scratch without any template",
        ],
      },
    ],
    imgUrl: "nfsc.jpg",
    mockupImg: "nfsc.jpg",
    webUrl: "https://northstate.ca",
    display: true,
  },
  {
    id: "yb-motion",
    title: "A Portfolio Website",
    brand: "Personal Portfolio",
    type: "personal",
    tech: ["Next.js", "Motion", "TypeScript", "Tailwind CSS"],
    intro: [
      "A Next.js powered portfolio, demonstrating my ability to create clean, efficient, and visually appealing web experiences.",
    ],
    imgUrl: "yb-motion.webp",
    mockupImg: "yb-motion.webp",
    webUrl: "https://yb-motion.netlify.app/",
    display: true,
  },
  {
    id: "docurealm",
    title: "Collaborative Document Editor",
    type: "personal",
    tech: ["Next.js"],
    intro: [
      "This is a collaborative document editor built with NextJS.",
      "Includes authentication and is fully responsive.",
      "Users can create, edit and delete documents.",
      "Users can also collaborate with other users in real time.",
    ],
    imgUrl: "docurealm.png",
    mockupImg: "docurealm.png",
    webUrl: "https://docurealm.vercel.app",
  },
  {
    id: "imprezons",
    title: "Note Creating App",
    brand: "Inspired by Notion",
    type: "personal",
    tech: ["Next.js"],
    intro: [
      "This is a note creating app built with NextJS.",
      "Includes authentication and is fully responsive.",
      "Dynamically renders the notes created by the user and option to publish the notes.",
    ],
    imgUrl: "imprezons.webp",
    mockupImg: "imprezons.webp",
    webUrl: "https://imprezons.vercel.app",
    display: true,
  },
  {
    id: "portfolio",
    title: "Portfolio Website",
    type: "personal",
    tech: ["Next.js", "Framer"],
    intro: [
      "Portfolio website including some standard animations.",
      "The animations are created using Framer Motion.",
    ],
    imgUrl: "ybnew.webp",
    mockupImg: "ybnew.webp",
    webUrl: "https://ybframer.netlify.app",
  },
  {
    id: "zentapon",
    title: "Zenta Flow Plan",
    brand: "Zentapon Pty. Ltd.",
    type: "professional",
    tech: ["React.js", "Node.js", "React Native"],
    intro: [
      "The application focuses on managing cashflow for present and future based on your current entries.",
      "Consists of utilities like guided tour, video player, drag/drop, Bank-Feed API Integration and more.",
      "Involves complex real time transactional calculations.",
    ],
    features: [
      {
        id: "feature1",
        name: "Interactive Charts & Dynamic Tables",
        image: true,
        description: [
          "Usage of interactive curve and bar charts",
          "Use of dynamic, sortable and expandable tables",
          "Import/Export transactions from any data file to custom output file",
        ],
      },
      {
        id: "feature2",
        name: "Plaid Integration",
        image: true,
        description: [
          "The website is integrated with Plaid API for users to get benefits from their own bank accounts",
          "Different scenarios that user can create to mock up a real bank like feature and estimated future earnings",
        ],
      },
    ],
    imgUrl: "zentapon.webp",
    mockupImg: "zentapon.webp",
    webUrl: "https://zentaflowplan.com",
    appUrl: "https://zentapon.com.au",
  },
  {
    id: "portfolio-yb",
    title: "Portfolio Website",
    brand: "Personal Portfolio",
    type: "personal",
    tech: ["Next.js"],
    intro: [
      "A Next.js powered portfolio, demonstrating my ability to create clean, efficient, and visually appealing web experiences.",
    ],
    imgUrl: "portfolio-yb.webp",
    mockupImg: "portfolio-yb.webp",
    webUrl: "https://portfolio-yb.netlify.app/",
  },
  {
    id: "exyofin",
    title: "Finance",
    brand: "Landing Page Template",
    type: "personal",
    tech: ["Vue.js"],
    intro: [
      "This website is kind of a one page template built with basic HTML, CSS and JavaScript code.",
      "Includes carousel and is fully responsive.",
    ],
    imgUrl: "exyofin.webp",
    mockupImg: "exyofin.webp",
    webUrl: "https://vt-exyofin.netlify.app/",
  },
];

export default PROJECTS;
